### ISSUE TITLE
Be able to specify the output directory for a JFR recording

### ISSUE THREAD

**Issue by rockwotj** [ktoso/sbt-jmh#108]

**Comment by ktoso** [comment]
PR would be awesome for this. Thanks in advance

**Comment by jiminhsieh** [comment]
@rockwotj After I walked through source code, I found this [L46](https://github.com/ktoso/sbt-jmh/blob/v0.2.27/extras/src/main/java/pl/project13/scala/jmh/extras/profiler/FlightRecordingProfiler.java#L46). So you could setup your output directory in system property - `jmh.jfr.saveTo`. If you get into interactive mode of sbt, you could setup thought this command - `set javaOptions ++= Seq("-Djmh.jfr.saveTo={your_directory}")`. Then JFR recording would be export to your directory.

@ktoso Do have any idea of this feature? Maybe I could try this one. :)

**Comment by ktoso** [comment]
Would be great if you could give it a shot, thanks!
