### ISSUE TITLE
missing v0.2.24 tag

### ISSUE THREAD

**Issue by matsu-chara** [ktoso/sbt-jmh#113]
sbt-jmh v0.2.24 was released
https://dl.bintray.com/sbt/sbt-plugin-releases/pl.project13.scala/sbt-jmh/scala_2.10/sbt_0.13/0.2.24/

but, tag is missing https://github.com/ktoso/sbt-jmh/tree/v0.2.24

**Comment by ktoso** [comment]
Thanks, fixed!
