### ISSUE TITLE
Cross compile with sbt 1.0.0-M5

### ISSUE THREAD

**Issue by lomigmegard** [ktoso/sbt-jmh#115]
See http://developer.lightbend.com/blog/2017-04-18-sbt-1-0-roadmap-and-beta1/

**Comment by ktoso** [comment]
Yeah, we definitely should start doing that I guess.
I'm a bit busy this week, could you help out with a PR?

**Comment by lomigmegard** [comment]
I am quite busy myself, just created this as a placeholder ;)
Will see this weekend if I can work on this.

**Comment by ktoso** [comment]
Would be great, thanks in advance :)

**Comment by jvican** [comment]
This would be very much appreciated. @lomigmegard Have you done some progress on it? We've recently cut sbt 1.0.0-M6, so I recommend cross-compiling to that one.

**Comment by ktoso** [comment]
Meh, having some issues in releasing, will try later again

**Comment by eed3si9n** [comment]
Any update on this?

**Comment by ktoso** [comment]
Anything but that wording please ;)
Was offline for a wedding and just came back to work. 
Yes will release this soon

**Comment by eed3si9n** [comment]
Sorry 🙏. I hope the wedding was fun. I'd be happy to help if you run into any troubles publishing the plugin in my morning time.

**Comment by ktoso** [comment]
Nah, you're perfectly right to ping here, don't worry. Just the phrase I really don't like 😉 Got an allergy on it since working on akka-http I guess...

Extras released, plugin will follow any moment now!

**Comment by ktoso** [comment]
Plugin released too, please try `0.2.26`! :)
