### ISSUE TITLE
publish for sbt 1.0.0

### ISSUE THREAD

**Issue by mosesn** [ktoso/sbt-jmh#123]
sbt 1.0.0 has dropped, can you release sbt-jmh for 1.0.0?

**Comment by xuwei-k** [comment]
I think sbt-jmh `0.2.27` support sbt 1.0. it depends on 1.0.0-RC2 but sbt 1.0.0-RC2 is compatible with 1.0.0 final.

**Comment by xuwei-k** [comment]
https://gitter.im/sbt/sbt-contrib?at=596c57230de4d2545e352519

> we intend to keep 1.0.0-RC2 bincompat with 1.0.0 final
that's how Mark Harrah shipped previous versions of sbt
and that's how CrossUtil is coded for sbt

**Comment by ktoso** [comment]
Yes, 0.27 should work. I'll check once back home today (JST)

**Comment by ktoso** [comment]
It'll work, I released explicitly for 1.0 too
