### ISSUE TITLE
Publishing to other repositories except Bintray DL

### ISSUE THREAD

**Issue by Z1kkurat** [ktoso/sbt-jmh#127]
Greetings!
As the title states, is it possible to publish plugin to any target except Bintray DL?
My company works with proxied repositories, and we are happy with ones such as Jcenter/maven central/typesafe repos (repos that can be proxied all at once). But Bintray DL is another story, as there are personal "organizations"("spaces") that require each one to be proxied separately.

**Comment by ktoso** [comment]
All sbt plugins are in one central repository so the worry about personal spaces is not a real one :)
You only have to proxy a single one, the blessed sbt one: dl.bintray.com/sbt/sbt-plugin-releases/

**Comment by ktoso** [comment]
(It is not possible to release sbt plugins to maven central because they don't follow the "maven style" of publishing (directory layout))

**Comment by Z1kkurat** [comment]
Thank you very much! I will discuss this with our devops.
