### ISSUE TITLE
gplv2 with cpe

### ISSUE THREAD

**Issue by fommil** [ktoso/sbt-jmh#128]
license is GPLv2 with classpath exception, same as OpenJDK. Not GPLv2 as you note in the source: http://openjdk.java.net/projects/code-tools/jmh/

Huge difference.

**Comment by fommil** [comment]
(also, if it really was GPLv2 your plugin would have to be GPLv2)

**Comment by ktoso** [comment]
Where exactly and what do you want to be changed, please open tickets that are easier to understand what you want from me in them ;-)

**Comment by ktoso** [comment]
If you just mean the comment then I fixed that, but please be less cryptic with ticket descriptions :wink:
