### ISSUE TITLE
why write tests in main?

### ISSUE THREAD

**Issue by fommil** [ktoso/sbt-jmh#129]
you've gone to all this effort to have a separate `jmh` config (which is absolutely the correct way to do it)... then you make people write their tests in `main`? .... Why?

It would be soooo much cleaner if jmh tests were written in a `src/jmh/scala/...` directory.

**Comment by fommil** [comment]
```
Processing 21 classes from /tmp/fommil-sbt/home/fommil/Projects/stalactite/target/scala-2.12/classes with "reflection" generator
Writing out Java source to /tmp/fommil-sbt/home/fommil/Projects/stalactite/target/scala-2.12/src_managed/jmh and resources to /tmp/fommil-sbt/home/fommil/Projects/stalactite/target/scala-2.12/resource_managed/jmh
Annotation generator had thrown the exception.
java.lang.NullPointerException
```

supporting putting the tests in a separate `jmh` subdir seems so obvious, is there some reason you've not done it? This seems to have hardcoded the `main` target dir.

Forking...

**Comment by ktoso** [comment]
Send in a PR, happy to merge that

**Comment by fommil** [comment]
It'll break the API for all users. I'd like to have a test interface too but those things are a pain to write.

**Comment by ktoso** [comment]
Make it an option ;)

**Comment by fommil** [comment]
I'll try it out for a while before maybe releasing as a plugin: https://gitlab.com/fommil/stalactite/merge_requests/41

Note that I'm using LGPLv3.
