### ISSUE TITLE
JFR profiler fails to record when there is no flame graph tool present

### ISSUE THREAD

**Issue by LGLO** [ktoso/sbt-jmh#137]
It seems that 0.3.0 fails when you don't have flame graph tool installed.
This is my invocation:
`jmh:run -prof jmh.extras.JFR -t1 -f1 -wi 1 -i 6 pl.lechglowiak.TryCatchBench`
It fails with:
```
[info] java.lang.NullPointerException
[info]  at pl.project13.scala.jmh.extras.profiler.FlightRecordingProfiler.createCollapsed(FlightRecordingProfiler.java:217)
[info]  at pl.project13.scala.jmh.extras.profiler.FlightRecordingProfiler.afterIteration(FlightRecordingProfiler.java:192)
[info]  at org.openjdk.jmh.runner.BenchmarkHandler.stopProfilers(BenchmarkHandler.java:272)
```
In 0.2.27 this invocation just works.

Shouldn't
https://github.com/ktoso/sbt-jmh/blob/master/extras/src/main/java/pl/project13/scala/jmh/extras/profiler/FlightRecordingProfiler.java#L192
be just 2 lines lower?

**Comment by ktoso** [comment]
Resolves by @retronym in https://github.com/ktoso/sbt-jmh/pull/138#issuecomment-351972951

**Comment by LGLO** [comment]
Thank you!

**Comment by ktoso** [comment]
Fix is on way to maven central and bintray, use 0.3.1 once it's out there 👍
