### ISSUE TITLE
Make sbt-jmh an AutoPlugin

### ISSUE THREAD

**Issue by ktoso** [ktoso/sbt-jmh#14]
Make it an autoplugin :-) http://www.scala-sbt.org/release/docs/Plugins.html

**Comment by hseeberger** [comment]
+1

**Comment by hseeberger** [comment]
I'm not going to create a PR, because you removed "help wanted" ;-)

**Comment by ktoso** [comment]
Probably by accident :-) please do :-)

**Comment by hseeberger** [comment]
Did it. See #35.
