### ISSUE TITLE
missing 0.3.0, 0.3.1, 0.3.2 tag on GitHub

### ISSUE THREAD

**Issue by xuwei-k** [ktoso/sbt-jmh#141]
- https://repo1.maven.org/maven2/pl/project13/scala/sbt-jmh-extras/
- https://github.com/ktoso/sbt-jmh/releases

![maven central](https://user-images.githubusercontent.com/389787/34663288-78b74284-f499-11e7-8185-47cd9699cfdd.png)
![github tags](https://user-images.githubusercontent.com/389787/34663289-78ecbce8-f499-11e7-85dd-a54bc4e21f5d.png)

**Comment by ktoso** [comment]
0.3.0 was dead on arrival I think... pushed the tags :)

**Comment by ktoso** [comment]
Thanks for noticing
