### ISSUE TITLE
Flame graph file names for parametrizied benchmarks should have suffixes with param-value pairs

### ISSUE THREAD

**Issue by plokhotnyuk** [ktoso/sbt-jmh#149]
Currently, files with flame graphs are just saved over each other with the same name.

As a workaround, you can specify all benchmark params to avoid running multiple attempts with different values.

As an option, it can be nested subdirectories for each param-value pairs.

But to resolve it properly need to cope with some escaping and truncation of values to fit file/directory naming limits.

**Comment by retronym** [comment]
Flamegraph support is retired here and now lives in JMH core, so closing this.
