### ISSUE TITLE
Version 0.3.5 JFR profile java.lang.UnsupportedClassVersionError on Java 8

### ISSUE THREAD

**Issue by lJoublanc** [ktoso/sbt-jmh#165]
When running with the java flight recorder profile, I get the following:

> [info] Running (fork) org.openjdk.jmh.Main -prof jmh.extras.JFR -t1 -f 1 -wi 3 -i 3
> [error] Exception in thread "main" java.lang.UnsupportedClassVersionError: jmh/extras/JFR has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0

This appears to work fine with JDK 11 though (however I don't have the as-yet-unreleased JMC 7 to read the files).

To the best of my understanding, I'm guessing that the published JARS were compiled on openJDK 11.

I've tried deleting my ivy cache and also ~/.sbt/1.0/plugins to see if this would cause the plugin to recompile the module. However, this didn't help.

Alternatively, is there an option to force jmh to output a certain JFR version for backward compat?

**Comment by lJoublanc** [comment]
I can confirm that after switching to 0.3.3., and `sbt clean`ing packages, this appears to work now.

**Comment by retronym** [comment]
Yes, the publishing for 0.3.4 and 0.3.5 was accidentally done with the wrong JDK version. We'll try again with 0.3.6 ASAP and report back here when its done.

**Comment by retronym** [comment]
Fixed on 0.3.7
