### ISSUE TITLE
CI broken: unable to install oraclejdk8

### ISSUE THREAD

**Issue by retronym** [ktoso/sbt-jmh#168]
https://api.travis-ci.org/v3/job/547479268/log.txt

```
Expected feature release number in range of 9 to 14, but got: 8
The command "~/bin/install-jdk.sh --target "/home/travis/oraclejdk8" --workspace "/home/travis/.cache/install-jdk" --feature "8" --license "BCL"" failed and exited with 3 during .
```

Did this regress in #163, or is it a general change in Travis?

**Comment by jiminhsieh** [comment]
It's a general change in Travis CI. [`sbt-native-packager` met the same issue.](https://travis-ci.org/sbt/sbt-native-packager/jobs/545737004#L166)

**Comment by retronym** [comment]
(currently unanswered) thread: https://travis-ci.community/t/error-installing-oraclejdk8-expected-feature-release-number-in-range-of-9-to-14-but-got-8/3766

**Comment by xuwei-k** [comment]
https://github.com/travis-ci/travis-ci/issues/10290#issuecomment-432331802

> `oraclejdk8` is not preinstalled on Xenial anymore, and cannot be retrieved from Oracle itself anymore. We'd suggest using either openjdk, or the currently supported Oracle JDK.

**Comment by retronym** [comment]
I switched back to Debian's trusty distro for now. OpenJDK 8 doesn't work for sbt-jmh's test of its Flight Recorder integration.

In the longer term, we should move of OracleJDK 8 in CI.

  - stop running the Flight Recorder test in, or
  - Run that test with OpenJDK11 or higher
     - But run the rest of the build with OpenJDK 8
     - or, rely on `{scalac,javac} -release 8 -target 8`
