### ISSUE TITLE
publish to maven central instead of bintray

### ISSUE THREAD

**Issue by xuwei-k** [ktoso/sbt-jmh#195]
😢 

- https://github.com/sbt/sbt/issues/6294
- https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

**Comment by ktoso** [comment]
Due to limitations by my employer I can't do much maintenance and publishing here.

I hope @johanandren would be able to help here?

**Comment by xuwei-k** [comment]
How would you like to transfer https://github.com/sbt organization? 🤔

**Comment by retronym** [comment]
We already have a home on OSS sonatype for this project, and @johanandren and I have publish permissions. Is this all we need to do to publish the SBT plugin there? https://github.com/ktoso/sbt-jmh/pull/196

**Comment by ktoso** [comment]
Thanks so much everyone for handling this @retronym @johanandren ! <3
