### ISSUE TITLE
Upgrade to JMH 1.4

### ISSUE THREAD

**Issue by sirthias** [ktoso/sbt-jmh#27]

**Comment by sirthias** [comment]
For some reason the JMH dependency in 0.1.8 is still onto 1.3.1:

```
[info] downloading https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/pl.project13.scala/sbt-jmh/scala_2.10/sbt_0.13/0.1.8/jars/sbt-jmh.jar ...
[info] 	[SUCCESSFUL ] pl.project13.scala#sbt-jmh;0.1.8!sbt-jmh.jar (2245ms)
[info] Done updating.
[info] Set current project to root (in build file:/Users/mathias/Documents/projects/triebitset/)
root > p benchmark
[info] Set current project to benchmark (in build file:/Users/mathias/Documents/projects/triebitset/)
benchmark > show libraryDependencies
[info] List(org.scala-lang:scala-library:2.11.5, org.openjdk.jmh:jmh-core:1.3.1, org.openjdk.jmh:jmh-generator-bytecode:1.3.1, org.openjdk.jmh:jmh-generator-reflection:1.3.1)
benchmark >
```

Maybe the JAR somehow didn't get rebuilt properly for the latest release?

**Comment by ktoso** [comment]
Hm... thanks for the info, I'll look into that today evening

**Comment by sirthias** [comment]
Thanks, Konrad!
Meanwhile JMH 1.5 has been released.
Maybe it's even possible to upgrade to that right away.

**Comment by ktoso** [comment]
Had a silly mistake in the 1.8 release: https://github.com/ktoso/sbt-jmh/commit/c20646bb2b796083558e26320fdf55dd7936a39b#diff-656d44ed3ab355d919402897bec8a9bdL44

Now fixed and released `0.1.9` with `1.5` support. Happy hakking!

**Comment by sirthias** [comment]
Great! Thanks!

One more (unrelated) question that I am just about to look into:
Do you know the best way to access the benchmark results programmatically?
It seems I need to get a `public static main` method into the benchmark class, which is not as easy as it should. I'm thinking a parent class written in Java which simply calls out to a Scala object could do the trick, but I might be missing something.

**Comment by ktoso** [comment]
Good and bad news for that one.

Good comes first. You can either just write a main class that invokes the runner explicitly, and then gets the results from a `run()`. You also can give a custom output formatter, as shown below.

```scala
package org.openjdk.jmh

import java.util

import org.openjdk.jmh._
import org.openjdk.jmh.infra.{IterationParams, BenchmarkParams}
import org.openjdk.jmh.results.{BenchmarkResult, RunResult, IterationResult}
import org.openjdk.jmh.runner.Runner
import org.openjdk.jmh.runner.format.OutputFormat
import org.openjdk.jmh.runner.options.CommandLineOptions

object RunnerApp extends App {
  import collection.JavaConversions._
  
  val opts = new CommandLineOptions(args: _*)
  
  val formatter = new OutputFormat {override def iteration(benchmarkParams: BenchmarkParams, iterationParams: IterationParams, i: Int): Unit = ???

    override def endBenchmark(benchmarkResult: BenchmarkResult): Unit = ???

    override def endRun(collection: java.util.Collection[RunResult]): Unit = ???

    override def flush(): Unit = ???

    override def write(i: Int): Unit = ???

    override def write(bytes: Array[Byte]): Unit = ???

    override def startBenchmark(benchmarkParams: BenchmarkParams): Unit = ???

    override def startRun(): Unit = ???

    override def close(): Unit = ???

    override def println(s: String): Unit = ???

    override def verbosePrintln(s: String): Unit = ???

    override def iterationResult(benchmarkParams: BenchmarkParams, iterationParams: IterationParams, i: Int, iterationResult: IterationResult): Unit = ???

    override def print(s: String): Unit = ???
  }
  
//  val runner = new Runner(opts, formatter)
  val runner = new Runner(opts)

  val res = runner.run()
  
  res.foreach { r ⇒
    println("r.getAggregatedResult = " + r.getAggregatedResult)
  }
  
}
```

Now bad news: It won't work "just like that"... Currently we'd get class not founds because of the generated classes not being on the classpath of when you `runMain` something. I think this should be solvable by adding `./target/scala-2.10/classes/` to the classpath for `runMain` hm. I'll create a ticket and look into it.

Other hints: depends what you're doing (getting programatic access becomes a ticket now ;-)),
maybe exporting to csv or json would be useful? That's just an option and would work now, the available output formats are: `[info] Available formats: text, csv, scsv, json, latex`.

**Comment by sirthias** [comment]
Great. Thanks for the info. I'll work something out and let you know...
