### ISSUE TITLE
Upgrade to JMH 1.6

### ISSUE THREAD

**Issue by sirthias** [ktoso/sbt-jmh#31]
@shipilev is moving fast (I guess being a perf guy this is expected).
By now JMH 1.6 is already out again for a few days and sbt-jmh needs another upgrade.

**Comment by ktoso** [comment]
Very fast indeed :-)

**Comment by sirthias** [comment]
10 Minutes.
Wow, someone else is moving fast as well... :)

**Comment by ktoso** [comment]
;-)

Happy hakking!
