### ISSUE TITLE
Unable to add jmhSettings

### ISSUE THREAD

**Issue by vijaykumargundavarapu** [ktoso/sbt-jmh#39]
Hi,

I tried adding jmhSettings to my build.sbt or build.scala but it never finds the reference even after importing  pl.project13.scala.sbt.SbtJmh._

Any idea how to add this jmhSettings to my scala project?

**Comment by ktoso** [comment]
Hi there, I've updated the docs - I assume you're using `0.1.15`, since this release sbt-jmh is an auto-plugin (see current readme to know what this is).

You don't need the importing now, just add the plugin and you're ready to roll.

**Comment by ktoso** [comment]
I'll close as solved, please do vigorously re-open if I assumed something wrong! :-)
