### ISSUE TITLE
How to run the benchmarks

### ISSUE THREAD

**Issue by vijaykumargundavarapu** [ktoso/sbt-jmh#40]
Hi,

I was able to set up the Auto Plugin in my project and now I am not sure how to execute a simple benchmark test on scala method.

Here is the example method I wrote in Scala

 
BenchMarkSample.scala
import org.openjdk.jmh.annotations.Benchmark

/**
 * Created by a567223 on 5/7/2015.
 */
class HelloWorld {

  @Benchmark
  def callBenchmark{
    println("******************WILL THIS BENCHMARK")
  }
}

Command I tried to use to run benchmark: sbt 
"run -i 10 .*BenchMarkSample.*"

**Comment by ktoso** [comment]
Yup, with 0.2.3 it's `jmh:run`
