### ISSUE TITLE
JmhPlugin is using a deprecated method

### ISSUE THREAD

**Issue by sergiotudela** [ktoso/sbt-jmh#48]
Hi,

While I was upgrading to JMH 1.10, I found that JmhPlugin is using a deprecated method https://github.com/ktoso/sbt-jmh/blob/master/src/main/scala/pl/project13/scala/sbt/JmhPlugin.scala#L118

> @deprecated("Use the `compile` method instead.", "0.13.8")

In case that SBT 0.13.6 was not supported anymore in this plugin, this warning should be fixed. So this issue should be considered in the future.

**Comment by ktoso** [comment]
Great, thanks for noticing - I think we could squeeze it in rather soon.

**Comment by jiminhsieh** [comment]
https://github.com/ktoso/sbt-jmh/blob/v0.2.1/src/main/scala/pl/project13/scala/sbt/JmhPlugin.scala#L118

**Comment by jiminhsieh** [comment]
I found the original source code already been removed a long time ago. It may close this ticket safely. This is the [commit](https://github.com/ktoso/sbt-jmh/commit/c49d49b564eb2d2dbbb2be3c41ac2197b977f574) removed using a deprecated method. By the way, the link was mentioned by @sergiotudela  was already outdated, there is the link - https://github.com/ktoso/sbt-jmh/blob/v0.2.1/src/main/scala/pl/project13/scala/sbt/JmhPlugin.scala#L118.

**Comment by ktoso** [comment]
Ah, great observation, thanks @jiminhsieh !
