### ISSUE TITLE
Support automatic flame-graph generation

### ISSUE THREAD

**Issue by ktoso** [ktoso/sbt-jmh#58]
Utilise https://github.com/jrudolph/perf-map-agent

**Comment by ktoso** [comment]
Hi @jrudolph, I finally got back to this pet project though am getting stuck at the same thing again.
You can check out the branch https://github.com/ktoso/sbt-jmh/tree/scala-in-flames and rnu `sbt scripted` in the main directory, it'll stop executing before it quits (as that cleans up the result), when that happens check out the `/tmp` for existing svg files and you'll notice the problem I'm struggling with now.

On one hand, I guess it relates to not being root...? However I believe the code does execute perf as root. Could this be one of those issues where the JVM we attach to must also be the same user? I don't think so, as when manually running that did not seem to be required..

You'll notice the code is rather messy, but once figured out can be made nicer.
It is a collection of downloading and preparing env (including the c agent) and attaching perf at the right moments etc, all the way through calling the flamegraph scrips to get the svg. I'm stuck at getting the "right" results into the svg, I'm getting lots of `[unknown]` which would indicate I'm not using the frame pointer, but I believe that's not the case - forked JVM clearly has the flag (and is JDK 1.8-60+ (77 in my case)).

If you could pop in and we could think about what could be the problem here that'd be awesome - would be awesome to have flamegraphs from macro benchmarks just like that.

**Comment by retronym** [comment]
Closing this on account of the async-profiler / JFR + Flamegraph integration.
