### ISSUE TITLE
Plugin version 2.4 depends on wrong version of JMH

### ISSUE THREAD

**Issue by mallman** [ktoso/sbt-jmh#60]
According to

https://github.com/ktoso/sbt-jmh/blob/185131ce460f864e8e5e1344c895e8fccfd41338/build.sbt#L17

the plugin is built against JMH 1.11. However, according to

https://github.com/ktoso/sbt-jmh/blob/c49d49b564eb2d2dbbb2be3c41ac2197b977f574/src/main/scala/pl/project13/scala/sbt/JmhPlugin.scala#L32

the plugin adds JMH 1.10.3 to the plugged-in project's library dependencies.

**Comment by ktoso** [comment]
Good catch, thanks – would you like to submit a PR to fix this (bump the version number)?
Thanks!

**Comment by mallman** [comment]
I believe a more DRY solution should be found for future versions of the plugin, but this PR gets the job done.

**Comment by ktoso** [comment]
Thanks for the PR!
