### ISSUE TITLE
sbt-jmh-extras should be published scala-version-agnostic

### ISSUE THREAD

**Issue by ktoso** [ktoso/sbt-jmh#76]
There's only Java code in there

**Comment by retronym** [comment]
IIRC, this might need https://github.com/sbt/sbt-doge to keep the release process convenient.

**Comment by ktoso** [comment]
Thanks for the link there, would have forgotten probably :)
From what I understood a recent chat about it that's correct :)

**Comment by retronym** [comment]
I ran into this in github.com/retronym/scala-jmh-suite trying to switch to as-yet unpublished Scala versions (which I want to benchmark).

Workaround is to add:

```scala
libraryDependencies := {
  libraryDependencies.value.map {
    case x if x.name == "sbt-jmh-extras" =>
      x.cross(CrossVersion.binaryMapped(_ => "2.11.8"))
    case x => x
  }
}
```

**Comment by ktoso** [comment]
Thanks for the ping.
I've made it be released without scala version now, so please upgrade to `0.2.14` (which uses https://repo1.maven.org/maven2/pl/project13/scala/sbt-jmh-extras/0.2.14/ should be online in a bit, once central sync finishes)
