### ISSUE TITLE
Fix examples link

### ISSUE THREAD

**Issue by calvinlfer** [ktoso/sbt-jmh#80]
Hello

[Examples](https://github.com/ktoso/sbt-jmh#examples) points to this link:
https://github.com/ktoso/sbt-jmh/tree/master/src/sbt-test/sbt-jmh/run/src/main/scala/org/openjdk/jmh/samples that does not work

**Comment by ktoso** [comment]
Could you fix the link in a PR?
Thanks a lot :)

I'm vacationing right now

**Comment by calvinlfer** [comment]
will do!

**Comment by ktoso** [comment]
Thanks a lot!
