### ISSUE TITLE
The with-FlightRecorderProfiler scripted test has versions mixed up

### ISSUE THREAD

**Issue by gkossakowski** [ktoso/sbt-jmh#86]
If you modify jmh-extras and run the `with-FlightRecorderProfiler` scripted test, the local modifications won't be picked up. The reason is that the scripted test doesn't set the version of extras so the default (non snapshot) version is used.

The workaround is:

``` patch
diff --git a/plugin/src/sbt-test/sbt-jmh/with-FlightRecorderProfiler/build.sbt b/plugin/src/sbt-test/sbt-jmh/with-FlightRecorderProfiler/build.sbt
index bb17cb1..601d9cc 100644
--- a/plugin/src/sbt-test/sbt-jmh/with-FlightRecorderProfiler/build.sbt
+++ b/plugin/src/sbt-test/sbt-jmh/with-FlightRecorderProfiler/build.sbt
@@ -1 +1,2 @@
 enablePlugins(JmhPlugin)
+extrasVersion in Jmh := sys.props("project.version")
```

**Comment by ktoso** [comment]
hey, thanks - good catch.
Do you want to PR that change or shall I apply myself?

**Comment by gkossakowski** [comment]
Go ahead. I'm happy spare that one line :)
