### ISSUE TITLE
README says version 0.2.19, but it doesn't exist

### ISSUE THREAD

**Issue by paulp** [ktoso/sbt-jmh#98]
It looks like `version.sbt` wasn't bumped, so there's no `0.2.19` at [bintray](https://dl.bintray.com/sbt/sbt-plugin-releases/pl.project13.scala/sbt-jmh/scala_2.10/sbt_0.13/) and maybe 0.2.18 was overwritten.

**Comment by ktoso** [comment]
Whoops, thanks for reporting. Will release in the morning.

**Comment by ktoso** [comment]
Released now, version bump sneaked in other PR but good to release with latest JMH in any case.
The extras lib needs a while to sync to maven central though.
